#!/usr/bin/env python3
"""課題別ダウンロード計画で使う素材だけを、3業種ZIPから静的配信用に抽出する。

入力:
  - lib/demo-task-download-plan.generated.json
  - public/downloads/demo-data/*.zip

出力:
  - public/downloads/demo-data/files/<industry>/<ASCII file name>
  - public/downloads/demo-data/direct-files-manifest.generated.json

`files/` はこのスクリプトだけが管理する。再生成時は固定マーカーを
確認し、別のディレクトリを誤って削除しない。
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import re
import shutil
import stat
import sys
import tempfile
import unicodedata
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
DEMO_ROOT = REPO_ROOT / "public" / "downloads" / "demo-data"
PLAN_PATH = REPO_ROOT / "lib" / "demo-task-download-plan.generated.json"
CATALOG_PATH = DEMO_ROOT / "catalog.json"
OUTPUT_ROOT = DEMO_ROOT / "files"
OUTPUT_MANIFEST = DEMO_ROOT / "direct-files-manifest.generated.json"

MARKER_NAME = ".aijuku-demo-direct-files-v1"
MARKER_CONTENT = (
    "Owned by scripts/extract_demo_direct_files.py\n"
    "This directory may be safely regenerated by that script only.\n"
)

PACKAGES = {
    "salon": {
        "file": "salon-demo-data-full-v1.zip",
        "root": "美容室デモデータ",
    },
    "construction": {
        "file": "construction-demo-data-full-v1.zip",
        "root": "建設業デモデータ",
    },
    "realestate": {
        "file": "real-estate-demo-data-full-v1.zip",
        "root": "不動産会社デモデータ",
    },
}

ALLOWED_EXTENSIONS = {".txt", ".docx", ".xlsx", ".pdf", ".csv", ".md"}
PUBLIC_FILE_PATTERN = re.compile(
    r"^[0-9a-f]{16}\.(?:txt|docx|xlsx|pdf|csv|md)$"
)
MAX_ENTRY_BYTES = 25 * 1024 * 1024
MAX_PACKAGE_BYTES = 128 * 1024 * 1024


def fail(message: str) -> None:
    raise SystemExit(f"[direct-files] {message}")


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"必要なファイルがありません: {path.relative_to(REPO_ROOT)}")
    except json.JSONDecodeError as error:
        fail(f"JSONを読めません: {path.relative_to(REPO_ROOT)}: {error}")


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_text(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value:
        fail(f"{label}が空、または文字列ではありません")
    return value


def validate_relative_path(value: str, label: str) -> str:
    if "\x00" in value or "\\" in value:
        fail(f"{label}に危険な文字があります: {value!r}")
    pure = PurePosixPath(value)
    if pure.is_absolute() or not pure.parts or any(part in {"", ".", ".."} for part in pure.parts):
        fail(f"{label}が安全な相対パスではありません: {value!r}")
    if unicodedata.normalize("NFC", value) != value:
        fail(f"{label}がNFC正規形ではありません: {value!r}")
    extension = PurePosixPath(value).suffix.lower()
    if extension not in ALLOWED_EXTENSIONS:
        fail(f"{label}に未対応の拡張子があります: {value!r}")
    return value


def validate_plan(plan: Any) -> list[dict[str, Any]]:
    if not isinstance(plan, dict) or plan.get("version") != 1:
        fail("ダウンロード計画のversionが1ではありません")
    assets = plan.get("assets")
    tasks = plan.get("tasks")
    stats_data = plan.get("stats")
    if not isinstance(assets, list) or not isinstance(tasks, dict) or not isinstance(stats_data, dict):
        fail("ダウンロード計画の形が正しくありません")
    if stats_data.get("uniqueAssets") != len(assets):
        fail("ダウンロード計画のuniqueAssets件数が合いません")
    if stats_data.get("tasks") != len(tasks):
        fail("ダウンロード計画のtasks件数が合いません")

    by_key: dict[str, dict[str, Any]] = {}
    public_urls: set[str] = set()
    destinations: set[tuple[str, str]] = set()

    for index, raw_asset in enumerate(assets):
        if not isinstance(raw_asset, dict):
            fail(f"assets[{index}]がオブジェクトではありません")
        industry = require_text(raw_asset.get("industry"), f"assets[{index}].industry")
        if industry not in PACKAGES:
            fail(f"assets[{index}]の業種が未知です: {industry}")
        original_path = validate_relative_path(
            require_text(raw_asset.get("originalPath"), f"assets[{index}].originalPath"),
            f"assets[{index}].originalPath",
        )
        key = require_text(raw_asset.get("key"), f"assets[{index}].key")
        expected_key = f"{industry}:{original_path}"
        if key != expected_key:
            fail(f"assets[{index}]のkeyが合いません: {key!r} != {expected_key!r}")
        if key in by_key:
            fail(f"素材keyが重複しています: {key}")

        public_file = require_text(raw_asset.get("publicFile"), f"assets[{index}].publicFile")
        if not public_file.isascii() or not PUBLIC_FILE_PATTERN.fullmatch(public_file):
            fail(f"publicFileがASCII安全形式ではありません: {public_file!r}")
        if Path(public_file).suffix.lower() != PurePosixPath(original_path).suffix.lower():
            fail(f"publicFileと元ファイルの拡張子が違います: {key}")

        public_url = require_text(raw_asset.get("publicUrl"), f"assets[{index}].publicUrl")
        expected_url = f"/downloads/demo-data/files/{industry}/{public_file}"
        if public_url != expected_url or not public_url.isascii():
            fail(f"publicUrlが安全な想定パスではありません: {public_url!r}")
        if public_url in public_urls:
            fail(f"publicUrlが重複しています: {public_url}")
        public_urls.add(public_url)
        destination = (industry, public_file)
        if destination in destinations:
            fail(f"抽出先が重複しています: {industry}/{public_file}")
        destinations.add(destination)
        by_key[key] = raw_asset

    task_file_count = 0
    referenced_keys: dict[str, set[str]] = {key: set() for key in by_key}
    for task_id, raw_task in tasks.items():
        if not isinstance(task_id, str) or not task_id or not isinstance(raw_task, dict):
            fail("課題別ダウンロード計画の形が正しくありません")
        industry = raw_task.get("industry")
        if industry not in PACKAGES:
            fail(f"{task_id}の業種が未知です: {industry!r}")
        task_files = raw_task.get("files")
        if not isinstance(task_files, list):
            fail(f"{task_id}.filesが配列ではありません")
        seen_in_task: set[str] = set()
        for raw_file in task_files:
            if not isinstance(raw_file, dict):
                fail(f"{task_id}.filesに不正な値があります")
            key = require_text(raw_file.get("assetKey"), f"{task_id}.files.assetKey")
            asset = by_key.get(key)
            if not asset:
                fail(f"{task_id}が未登録素材を参照しています: {key}")
            if key in seen_in_task:
                fail(f"{task_id}内で素材が重複しています: {key}")
            seen_in_task.add(key)
            if industry != asset["industry"]:
                fail(f"{task_id}の業種と素材の業種が違います: {key}")
            for plan_field, asset_field in (
                ("originalPath", "originalPath"),
                ("publicFile", "publicFile"),
                ("publicUrl", "publicUrl"),
            ):
                if raw_file.get(plan_field) != asset.get(asset_field):
                    fail(f"{task_id}の{plan_field}がassetsと一致しません: {key}")
            referenced_keys[key].add(task_id)
            task_file_count += 1

    if stats_data.get("taskFiles") != task_file_count:
        fail("ダウンロード計画のtaskFiles件数が合いません")
    for key, asset in by_key.items():
        if not referenced_keys[key]:
            fail(f"どの課題からも使われない素材があります: {key}")
        task_ids = asset.get("taskIds")
        if not isinstance(task_ids, list) or set(task_ids) != referenced_keys[key]:
            fail(f"{key}のtaskIdsが課題参照と一致しません")

    return assets


def catalog_packages(catalog: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(catalog, dict) or not isinstance(catalog.get("packages"), list):
        fail("デモデータカタログの形が正しくありません")
    result: dict[str, dict[str, Any]] = {}
    for package in catalog["packages"]:
        if not isinstance(package, dict):
            fail("デモデータカタログに不正なパッケージがあります")
        industry = package.get("industry")
        if industry in result:
            fail(f"カタログの業種が重複しています: {industry!r}")
        if industry not in PACKAGES:
            fail(f"カタログに未知の業種があります: {industry!r}")
        result[industry] = package
    if set(result) != set(PACKAGES):
        fail("カタログの業種一覧が想定と違います")
    return result


def validate_archive(
    industry: str,
    zip_path: Path,
    expected_root: str,
) -> tuple[zipfile.ZipFile, dict[str, zipfile.ZipInfo], dict[str, dict[str, str]]]:
    try:
        archive = zipfile.ZipFile(zip_path)
    except (FileNotFoundError, zipfile.BadZipFile) as error:
        fail(f"ZIPを開けません: {zip_path.relative_to(REPO_ROOT)}: {error}")

    entries: dict[str, zipfile.ZipInfo] = {}
    total_bytes = 0
    for info in archive.infolist():
        name = info.filename
        if "\x00" in name or "\\" in name:
            fail(f"{zip_path.name}に危険なZIPパスがあります: {name!r}")
        pure = PurePosixPath(name)
        if pure.is_absolute() or ".." in pure.parts or not pure.parts:
            fail(f"{zip_path.name}にZIP slipとなるパスがあります: {name!r}")
        if pure.parts[0] != expected_root:
            fail(f"{zip_path.name}のルートが違います: {name!r}")
        if unicodedata.normalize("NFC", name) != name:
            fail(f"{zip_path.name}にNFC正規形でない名前があります: {name!r}")
        mode = info.external_attr >> 16
        if stat.S_ISLNK(mode):
            fail(f"{zip_path.name}にシンボリックリンクがあります: {name!r}")
        if info.flag_bits & 0x1:
            fail(f"{zip_path.name}に暗号化ファイルがあります: {name!r}")
        if info.is_dir():
            continue

        relative = PurePosixPath(*pure.parts[1:]).as_posix()
        validate_relative_path(relative, f"{zip_path.name}内パス")
        if relative in entries:
            fail(f"{zip_path.name}内のパスが重複しています: {relative}")
        if info.file_size <= 0:
            fail(f"{zip_path.name}に空ファイルがあります: {relative}")
        if info.file_size > MAX_ENTRY_BYTES:
            fail(f"{zip_path.name}内のファイルが{MAX_ENTRY_BYTES} bytesを超えます: {relative}")
        total_bytes += info.file_size
        entries[relative] = info

    if total_bytes > MAX_PACKAGE_BYTES:
        fail(f"{zip_path.name}の展開容量が{MAX_PACKAGE_BYTES} bytesを超えます")

    manifest_info = entries.get("manifest.csv")
    if not manifest_info:
        fail(f"{zip_path.name}にmanifest.csvがありません")
    try:
        manifest_text = archive.read(manifest_info).decode("utf-8-sig")
    except (UnicodeDecodeError, zipfile.BadZipFile) as error:
        fail(f"{zip_path.name}のmanifest.csvを読めません: {error}")
    reader = csv.DictReader(io.StringIO(manifest_text))
    expected_fields = ["path", "format", "bytes", "sha256", "notice"]
    if reader.fieldnames != expected_fields:
        fail(f"{zip_path.name}のmanifest.csv列が想定と違います")
    internal_manifest: dict[str, dict[str, str]] = {}
    for row in reader:
        path = validate_relative_path(row["path"], f"{zip_path.name} manifest path")
        if path in internal_manifest:
            fail(f"{zip_path.name}のmanifest.csvが重複しています: {path}")
        internal_manifest[path] = row

    return archive, entries, internal_manifest


def assert_owned_output_root(*, must_exist: bool) -> None:
    if not OUTPUT_ROOT.exists() and not OUTPUT_ROOT.is_symlink():
        if must_exist:
            fail(f"抽出先がありません: {OUTPUT_ROOT}")
        return
    if OUTPUT_ROOT.is_symlink() or not OUTPUT_ROOT.is_dir():
        fail(f"抽出先が通常のディレクトリではありません: {OUTPUT_ROOT}")
    marker = OUTPUT_ROOT / MARKER_NAME
    if marker.is_symlink() or not marker.is_file():
        fail(f"抽出先に所有マーカーがないため再生成を中止します: {marker}")
    if marker.read_text(encoding="utf-8") != MARKER_CONTENT:
        fail(f"抽出先の所有マーカーが一致しません: {marker}")


def main() -> int:
    check_mode = "--check" in sys.argv[1:]
    unknown_arguments = [arg for arg in sys.argv[1:] if arg != "--check"]
    if unknown_arguments:
        fail(f"未知の引数です: {' '.join(unknown_arguments)}")

    plan = load_json(PLAN_PATH)
    assets = validate_plan(plan)
    catalog = catalog_packages(load_json(CATALOG_PATH))
    assert_owned_output_root(must_exist=check_mode)

    if not check_mode:
        OUTPUT_ROOT.parent.mkdir(parents=True, exist_ok=True)
    staging = (
        None
        if check_mode
        else Path(
            tempfile.mkdtemp(prefix=".direct-files-staging-", dir=OUTPUT_ROOT.parent)
        )
    )
    manifest_assets: dict[str, dict[str, Any]] = {}

    try:
        if staging:
            (staging / MARKER_NAME).write_text(MARKER_CONTENT, encoding="utf-8")
        for industry, package in PACKAGES.items():
            zip_path = DEMO_ROOT / package["file"]
            catalog_package = catalog[industry]
            if catalog_package.get("file") != package["file"]:
                fail(f"{industry}のZIP名がカタログと違います")
            expected_bytes = catalog_package.get("bytes")
            if not isinstance(expected_bytes, int) or zip_path.stat().st_size != expected_bytes:
                fail(f"{zip_path.name}のバイト数がカタログと違います")
            expected_zip_sha = catalog_package.get("sha256")
            if not isinstance(expected_zip_sha, str) or sha256_file(zip_path) != expected_zip_sha:
                fail(f"{zip_path.name}のSHA-256がカタログと違います")

            archive, entries, internal_manifest = validate_archive(
                industry, zip_path, package["root"]
            )
            try:
                for asset in (item for item in assets if item["industry"] == industry):
                    key = asset["key"]
                    original_path = asset["originalPath"]
                    info = entries.get(original_path)
                    if not info:
                        fail(f"{key}が{zip_path.name}にありません")
                    internal = internal_manifest.get(original_path)
                    if not internal:
                        fail(f"{key}が{zip_path.name}のmanifest.csvにありません")
                    try:
                        payload = archive.read(info)
                    except zipfile.BadZipFile as error:
                        fail(f"{key}のZIPデータが壊れています: {error}")
                    if not payload:
                        fail(f"{key}は空ファイルです")
                    digest = sha256_bytes(payload)
                    if internal.get("bytes") != str(len(payload)):
                        fail(f"{key}のバイト数がmanifest.csvと違います")
                    if internal.get("sha256") != digest:
                        fail(f"{key}のSHA-256がmanifest.csvと違います")

                    destination = (
                        OUTPUT_ROOT if check_mode else staging
                    ) / industry / asset["publicFile"]
                    if not check_mode:
                        destination.parent.mkdir(parents=True, exist_ok=True)
                        destination.write_bytes(payload)
                    elif destination.is_symlink() or not destination.is_file():
                        fail(f"{key}の公開ファイルがありません: {destination}")
                    if destination.stat().st_size != len(payload):
                        fail(f"{key}の抽出後バイト数がZIPと違います")
                    if sha256_file(destination) != digest:
                        fail(f"{key}の抽出後SHA-256がZIPと違います")

                    manifest_assets[key] = {
                        "assetKey": key,
                        "originalPath": original_path,
                        "industry": industry,
                        "publicFile": asset["publicFile"],
                        "publicUrl": asset["publicUrl"],
                        "bytes": len(payload),
                        "sha256": digest,
                    }
            finally:
                archive.close()

        if len(manifest_assets) != len(assets):
            fail(f"抽出数が計画と違います: {len(manifest_assets)}/{len(assets)}")
        expected_files = {
            f"{asset['industry']}/{asset['publicFile']}" for asset in assets
        }
        actual_root = OUTPUT_ROOT if check_mode else staging
        if actual_root is None:
            fail("抽出先の内部状態が不正です")
        for path in actual_root.rglob("*"):
            if path.is_symlink():
                fail(f"抽出先にシンボリックリンクがあります: {path}")
            if not path.is_dir() and not path.is_file():
                fail(f"抽出先に通常でないファイルがあります: {path}")
        actual_files = {
            path.relative_to(actual_root).as_posix()
            for path in actual_root.rglob("*")
            if path.is_file() and path.name != MARKER_NAME
        }
        if actual_files != expected_files:
            missing = sorted(expected_files - actual_files)[:5]
            extra = sorted(actual_files - expected_files)[:5]
            fail(
                "抽出ディレクトリのファイル一覧が計画と違います: "
                f"不足例={missing} / 余剰例={extra}"
            )
        expected_directories = {asset["industry"] for asset in assets}
        actual_directories = {
            path.relative_to(actual_root).as_posix()
            for path in actual_root.iterdir()
            if path.is_dir()
        }
        nested_directories = [
            path.relative_to(actual_root).as_posix()
            for path in actual_root.rglob("*")
            if path.is_dir() and path.parent != actual_root
        ]
        if actual_directories != expected_directories or nested_directories:
            fail(
                "抽出ディレクトリのフォルダ一覧が計画と違います: "
                f"直下={sorted(actual_directories)} / 多階層={sorted(nested_directories)[:5]}"
            )

        manifest = {
            "version": 1,
            "sourcePlanVersion": plan["version"],
            "stats": {
                "assets": len(assets),
                "bytes": sum(item["bytes"] for item in manifest_assets.values()),
                "industries": {
                    industry: sum(
                        1 for item in manifest_assets.values() if item["industry"] == industry
                    )
                    for industry in PACKAGES
                },
            },
            "assets": [manifest_assets[asset["key"]] for asset in assets],
        }
        manifest_text = json.dumps(manifest, ensure_ascii=False, indent=1) + "\n"

        if check_mode:
            try:
                current_manifest = OUTPUT_MANIFEST.read_text(encoding="utf-8")
            except FileNotFoundError:
                fail(f"直接配信マニフェストがありません: {OUTPUT_MANIFEST}")
            if current_manifest != manifest_text:
                fail(
                    "直接配信マニフェスがZIPとダウンロード計画に"
                    "一致しません。書込みモードで再生成してください。"
                )
        else:
            manifest_fd, manifest_temp_name = tempfile.mkstemp(
                prefix=".direct-files-manifest-",
                suffix=".json",
                dir=OUTPUT_MANIFEST.parent,
            )
            try:
                with os.fdopen(manifest_fd, "w", encoding="utf-8") as handle:
                    handle.write(manifest_text)
                if OUTPUT_ROOT.exists():
                    shutil.rmtree(OUTPUT_ROOT)
                if staging is None:
                    fail("抽出先の内部状態が不正です")
                os.replace(staging, OUTPUT_ROOT)
                staging = None
                os.replace(manifest_temp_name, OUTPUT_MANIFEST)
            finally:
                if os.path.exists(manifest_temp_name):
                    os.unlink(manifest_temp_name)
    finally:
        if staging is not None and staging.exists():
            shutil.rmtree(staging)

    verb = "Verified" if check_mode else "Extracted"
    print(
        f"{verb} {len(assets)} direct files "
        f"({sum(item['bytes'] for item in manifest_assets.values())} bytes)"
    )
    print(f"Manifest: {OUTPUT_MANIFEST.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
